version: '3'

services:
  dogs: 
    build: ./dogs-service
    volumes:
      - ./dogs-service:/app
      - /app/node_modules
      
  competitions: 
    build: ./competitions-service
    volumes:
      - ./competitions-service:/app
      - /app/node_modules
      
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dogs
      - competitions